version: '2.1'
services:
  eventum-comment-ms:
    container_name: eventum-comment-ms
    build: .
    links: eventum-comment-db
    depends_on:
      eventum-comment-db: 
        condition: service_healthy
    ports:
      - "8002:8002"
 
      

