version: '2.1'
services:
  eventum-comment-ms:
    container_name: eventum-comment-ms
    build: .
    ports:
      - "8002:8002"
    environment: # Definición de variables de entorn
      DB_CONNECTION: mysql
      DB_HOST: ev-comments-service-clusterip
      DB_PORT: 3306
      DB_DATABASE: eventum
      DB_USERNAME: larauser
      DB_PASSWORD: P@ssword0000