version: '2.1'
services:
  eventum-comment-ms:
    container_name: eventum-comment-ms
    build: .
    links: eventum-comment-db
    
    ports:
      - "8002:8002"
    environment: # Definición de variables de entorn
      DB_CONNECTION: mysql
      DB_HOST: 192.168.0.1
      DB_PORT: 3307
      DB_DATABASE: eventum
      DB_USERNAME: larauser
      DB_PASSWORD: P@ssword0000